databases:
  - name: blog-database
    plan: free
    databaseName: blog_database
    user: adacorp

services:
  - type: web
    name: blog
    plan: free
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn blog.asgi:application -k uvicorn.workers.UvicornWorker --preload
    postDeployCommand: |
      cd blog
      python manage.py migrate
      python manage.py createsuperuser --noinput || true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blog-database
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: RENDER
        value: "1"
      - key: DEBUG
        value: "0"
      - key: DJANGO_SUPERUSER_USERNAME
        value: "admin"
      - key: DJANGO_SUPERUSER_EMAIL
        value: "ajane717@gmail.com"
      - key: DJANGO_SUPERUSER_PASSWORD
        value: "my_super_strong_password147"
